resolver: nightly-2019-09-30

packages:
  - .

extra-deps:
  - git: https://github.com/sebeaumont/direct-sqlite.git
    commit: ca4762576cb331bba212660e61f44643c435f890
  - git: https://github.com/sebeaumont/sqlite-simple.git
    commit: 733fcecc5dd9336baa1f6a072c11375b1b61165c

flags:
  direct-sqlite:
    systemlib: true

extra-lib-dirs: 
  - /usr/local/opt/sqlite3/lib 
  - /usr/local/lib